### ISSUE TITLE
Can you submit the code for KAKURENBO as soon as possible?

### ISSUE THREAD

**Issue by ChaohuaYang** [TruongThaoNguyen/kakurenbo#1]
Hello, first of all, congratulations on your paper being accepted by NIPS; that's really impressive! I recently read your paper and found the idea to be excellent. However, there are certain parts that I didn't quite grasp, and I'm curious about the specific implementation details. As a result, I'm interested in taking a look at the code for this work. Unfortunately, it seems that you haven't completely open-sourced the code for this project yet. I was wondering if you could consider open-sourcing the code as soon as possible. I believe this would greatly assist me in gaining a deeper understanding of KAKURENBO, and I would be very grateful for that.

**Comment by TruongThaoNguyen** [comment]
Thank you for your attention on this work. We are under the process for approval of publishing the code. If you have question, please let me know through email. I will try to explain it to you

**Comment by ChaohuaYang** [comment]
Thank you for your reply. I was wondering if you could send me a copy of the code for this work, incomplete doesn't matter, I want to use KAKURENBO as the baseline for my next work, so I'd like to see the code implementation. Please be assured that I only use the code for personal learning and will not make the code public. If you like, you can send the code to ych981203@gmail.com. Thank you very much for your support. Please forgive me if you feel offended and thank you for your understanding.

**Comment by TruongThaoNguyen** [comment]
Sorry for the delay. Please enjoy the code. It is not perfect but I think somehow it could help you to understanding our idea.
